feature_scaling:
  # "normalize" | "standardize" | "raw"
  day_cos: raw
  day_sin: raw
  long: normalize
  lat: normalize
  lst_avg: normalize
  height_avg: standardize
  height_diffs: standardize

model: